#    ╻  ┏━┓╻ ╻┏━┓╻ ╻╺┳╸
#    ┃  ┣━┫┗┳┛┃ ┃┃ ┃ ┃
#    ┗━╸╹ ╹ ╹ ┗━┛┗━┛ ╹

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    orientation = right
}

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = false
  pass_mouse_when_bound = false
}

scrolling {
    fullscreen_on_one_column = true
    follow_min_visible = 1
    direction = down
    column_width = 0.333
    explicit_column_widths = 0.333, 0.5, 0.667
}
