#    ┏━┓╻ ╻╺┳╸┏━┓┏━┓╺┳╸┏━┓┏━┓╺┳╸
#    ┣━┫┃ ┃ ┃ ┃ ┃┗━┓ ┃ ┣━┫┣┳┛ ┃
#    ╹ ╹┗━┛ ╹ ┗━┛┗━┛ ╹ ╹ ╹╹┗╸ ╹

# Setup XDG for screen sharing and start waypaper
exec-once = ~/.config/hypr/scripts/xdg.sh

# Start Quickshell
exec-once = qs -c /home/b/.config/quickshell/neo

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Wallpaper
exec-once = swww-daemon

# Load up vicinae
exec-once = vicinae server

# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh
