#    ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻   ┏━┓╻ ╻╻  ┏━╸┏━┓
#    ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃   ┣┳┛┃ ┃┃  ┣╸ ┗━┓
#    ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛   ╹┗╸┗━┛┗━╸┗━╸┗━┛

# -----------------------------------------------------
# Floating Rules
# -----------------------------------------------------

# Waypaper
windowrule = float,class:(.*waypaper.*)
windowrule = size 900 700,class:(.*waypaper.*)
windowrule = center,class:(.*waypaper.*)
windowrule = pin,class:(.*waypaper.*)

# Pavucontrol floating
windowrule = float,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = center,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = pin,class:(.*org.pulseaudio.pavucontrol.*)

# Blueman Manager
windowrule = float,class:(blueman-manager)
windowrule = size 800 600,class:(blueman-manager)
windowrule = center,class:(blueman-manager)

# System Mission Center Preference Window
windowrule = float, class:(missioncenter), title:^(Preferences)$
windowrule = pin, class:(missioncenter), title:^(Preferences)$
windowrule = center, class:(missioncenter), title:^(Preferences)$

# -----------------------------------------------------
# Blur Rules
# -----------------------------------------------------

# QuickShell
layerrule = blur,^(quickshell:bar:blur)$
layerrule = blur,^(quickshell:volpopup:blur)$
layerrule = blur,^(quickshell:wspopup:blur)$

# Sherlock
layerrule = blur,sherlock
layerrule = ignorealpha 0, sherlock

# Vicinae
layerrule = blur,vicinae
layerrule = ignorealpha 0, vicinae

# -----------------------------------------------------
# Opacity Rules
# -----------------------------------------------------

windowrulev2 = opacity 1.00 override, title:^(Picture-in-Picture)$

# -----------------------------------------------------
# Title Rules
# -----------------------------------------------------

windowrule = tile, title:^(Firefox)$

# -----------------------------------------------------
# Idleinhibit Rules
# -----------------------------------------------------

windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen
