#    ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸┏━┓
#    ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸ ┗━┓
#    ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸┗━┛
#    https://wiki.hypr.land/Configuring/Workspace-Rules/

# Assigning workspace to a certain monitor.
workspace = 1, name:P1, monitor:DP-1,default:true
workspace = 2, name:P2, monitor:DP-1
workspace = 3, name:P3, monitor:DP-1
workspace = 4, name:S1, monitor:DP-2,default:true
workspace = 5, name:S2, monitor:DP-2
workspace = 6, name:S3, monitor:DP-2
workspace = special:scratchpad, on-created-empty:nautilus
